### PR TITLE
Update general-settings.md

### PR DESCRIPTION
**Pull request by gweddle-nz**
Added a note about restarting the unicorn service after changing site URL so that auto-mailers have the correct link (e.g. user sign up verification email).

### CODE REVIEW

**Review by myriamboure — CHANGES_REQUESTED** [review]
@gweddle-nz this super admin guide is mainly used by non technical people. The place for technical aspects are more on the Github wiki of the OFN code. I understand it might be useful in that document but I have two change request then:
1- If you leave that comment, please add a sentence like "If you are not technical, contact the global sys admin team on how to get support" (with redirect maybe to that page : https://ofn-user-guide.gitbook.io/ofn-super-admin-guide/deployment-and-system-administration)
2- I'm wondering if that wouldn't be rather something to document in the OFN install github wiki ? I think it would be more relevant to specify that there, and maybe link this OFN install wiki more generally in the introduction of this super-admin handbook.

What do you think ?

**Comment by gweddle-nz** [comment]
@myriamboure I think your 2nd option makes the most sense. I will see what I can do. Sorry, I'm new to Github so I'm still getting my head around how it all works.

**Comment by myriamboure** [comment]
Great @gweddle-nz your feedbacks and contribution are really appreciated ! I'll leave that PR open for now, let me know when you have added that to the OFN-install wiki :-) Else we can of course rediscuss, if you felt that info was missing somewhere, it probably does so let's add it where it is relevant, and your view is really useful :-)

**Comment by RachL** [comment]
I'm closing this as I guess it has been taking care of :)

**Pull request closed without merging**
